/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ReportRouteImport } from './routes/report'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppInstagramRouteImport } from './routes/_app/instagram'
import { Route as AppLinkedinRouteImport } from './routes/_app/linkedin'
import { Route as AppSourcesRouteImport } from './routes/_app/sources'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInstagramRoute = AppInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AppRoute,
} as any)
const AppLinkedinRoute = AppLinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/report': typeof ReportRoute
  '/instagram': typeof AppInstagramRoute
  '/linkedin': typeof AppLinkedinRoute
  '/sources': typeof AppSourcesRoute
}
export interface FileRoutesByTo {
  '/report': typeof ReportRoute
  '/instagram': typeof AppInstagramRoute
  '/linkedin': typeof AppLinkedinRoute
  '/sources': typeof AppSourcesRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/report': typeof ReportRoute
  '/_app/instagram': typeof AppInstagramRoute
  '/_app/linkedin': typeof AppLinkedinRoute
  '/_app/sources': typeof AppSourcesRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/report' | '/instagram' | '/linkedin' | '/sources'
  fileRoutesByTo: FileRoutesByTo
  to: '/report' | '/instagram' | '/linkedin' | '/sources' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/report'
    | '/_app/instagram'
    | '/_app/linkedin'
    | '/_app/sources'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ReportRoute: typeof ReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instagram': {
      id: '/_app/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof AppInstagramRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/linkedin': {
      id: '/_app/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof AppLinkedinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInstagramRoute: typeof AppInstagramRoute
  AppLinkedinRoute: typeof AppLinkedinRoute
  AppSourcesRoute: typeof AppSourcesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInstagramRoute: AppInstagramRoute,
  AppLinkedinRoute: AppLinkedinRoute,
  AppSourcesRoute: AppSourcesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ReportRoute: ReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
